### ISSUE TITLE
Error when trying to install LB110(US) bulbs

### ISSUE THREAD

**Issue by medbox1** [DaveGut/Prototype-HUB-LESS-TP-Link-SmartThings-Device-Handlers#1]
works great for the HS100 switch but cannot install LB110(US) bulbs. 
"Unexpected error" pop-up

**Comment by DaveGut** [comment]
I had an error in the Smart App.  It is now corrected.  Try again.  (The error is I changed the default device handler for the HS110, but forgot to update the listing in the install section.  If ok, please reply back.

Dave

**Comment by medbox1** [comment]
Hi Dave
Still getting same error “Unexpected Error” when trying to add LB110 devices.
thanks for your efforts!!
Itay

**Comment by DaveGut** [comment]
Apologies if you have already done the below.

Assure you upload the 'TPLinkHS-Series.groovy' device handler.  Install the device, and then upload the HS0110EM version and change the driver in the device (as shown at the bottom of the instructions).  This was necessary since not everyone wanted the Energy Monitor functions - so the HS-Series was selected as the default.

**Comment by DaveGut** [comment]
Apologize for the inconvenience.

**Comment by medbox1** [comment]
The plug (HS) works perfectly. The error pops up when trying to install the smart bulbs (LB110US).
Thanks!

**Comment by medbox1** [comment]
This is the error log from app1.smartthings when trying to add TP-link bulbs if that helps:-)
8:07:34 AM: trace getPhrases(), state.welcomeIssue = null
 8:07:34 AM: error physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'TP-LinkLB110-110' in namespace 'beta' not found. @ line 184
 8:07:23 AM: trace getPhrases(), state.welcomeIssue = null

**Comment by DaveGut** [comment]
BLUSH!.  Too early here in Dallas.  There was a typo in the service manager.  Now fixed on site, or you can fix yourself.  In the code, you will see:

def addDevices() {
	def tpLinkModel = [:]
	tpLinkModel << ["HS100" : "TP-LinkHS-Series"]
	tpLinkModel << ["HS105" : "TP-LinkHS-Series"]
	tpLinkModel << ["HS110" : "TP-LinkHS-Series"]
	tpLinkModel << ["HS200" : "TP-LinkHS-Series"]
	tpLinkModel << ["LB100" : "TP-LinkLB100-110"]
	**tpLinkModel << ["LB110" : "TP-LinkLB110-110"]**
	tpLinkModel << ["LB120" : "TP-LinkLB120"]
        tpLinkModel << ["LB130" : "TP-LinkLB130"]

The bold line should read:  tpLinkModel << ["LB100" : "TP-LinkLB100-110"]

**Comment by medbox1** [comment]
Same error…

**Comment by DaveGut** [comment]
Problem with not having an actual device to test (I have everything except the LB100, 110.  Found another typo in the DEVICE HANDLER.  Updated on server.  In the Device hander, near the top, you will see:

metadata {
	**definition (name: "TP-LinkLB110-120", namespace: "beta", author: "Dave Gutheinz") {**
		capability "Switch"
		capability "Switch Level"
		capability "refresh"
		capability "Sensor"
		capability "Actuator"
	}

Change to read:  definition (name: "TP-LinkLB100-110", namespace: "beta", author: "Dave Gutheinz") {


SORRY FOR MY ERRORS!.

**Comment by medbox1** [comment]
It works!! yeepy!
Many thanks for all your efforts!!
Itay

**Comment by DaveGut** [comment]
Mu pleasure.  I will close the issue.  Thanks for your patience.
